#!/bin/bash

#new_extention=".py"
#if [ $# == 1 ]; then
#    filepath_with_local_extention=$1
#    filepath_with_new_extention=${filepath_with_local_extention%.*}$new_extention
#    python local.py $1 > $filepath_with_new_extention
#else
#    filepath_with_local_extention=$2
#    filepath_with_new_extention=${filepath_with_local_extention%.*}$new_extention
    python local.py $1 $2 
#> $filepath_with_new_extention    
#fi