# lextab.py. This file automatically created by PLY (version 3.4). Don't edit!
_tabversion   = '3.4'
_lextokens    = {'THEN': 1, 'ELIF': 1, 'RETURN': 1, 'READ': 1, 'IN': 1, 'NUMBER': 1, 'LBRACKET': 1, 'WHILE': 1, 'PRINT': 1, 'DIST': 1, 'OPEN': 1, 'MINUS': 1, 'DEF': 1, 'RBRACE': 1, 'LE': 1, 'RPAREN': 1, 'POWER': 1, 'NE': 1, 'LT': 1, 'PLUS': 1, 'COMMA': 1, 'STRING': 1, 'GT': 1, 'DIVIDE': 1, 'FOR': 1, 'EQUALS': 1, 'PERIOD': 1, 'ELSE': 1, 'GE': 1, 'LPAREN': 1, 'PASS': 1, 'TIMES': 1, 'ID': 1, 'IF': 1, 'AND': 1, 'LBRACE': 1, 'SEMI': 1, 'BREAK': 1, 'CONTINUE': 1, 'EXIT': 1, 'NOT': 1, 'RBRACKET': 1, 'OR': 1}
_lexreflags   = 0
_lexliterals  = ''
_lexstateinfo = {'INITIAL': 'inclusive'}
_lexstatere   = {'INITIAL': [('(?P<t_NEWLINE>\\n+)|(?P<t_ID>[A-Za-z_][\\w_]*)|(?P<t_comment>/\\*(.|\\n)*?\\*/)|(?P<t_PLUSPLUS>\\+\\+)|(?P<t_TIMESEQUAL>\\*=)|(?P<t_AND>and)|(?P<t_NOT>not)|(?P<t_OREQUAL>\\|=)|(?P<t_PLUSEQUAL>\\+=)|(?P<t_XOREQUAL>^=)|(?P<t_LE><=)|(?P<t_LBRACKET>\\[)|(?P<t_NE>!=)|(?P<t_RBRACE>\\})|(?P<t_MINUSEQUAL>-=)|(?P<t_EQ>==)|(?P<t_MINUSMINUS>--)|(?P<t_MODEQUAL>%=)|(?P<t_LPAREN>\\()|(?P<t_OR>or)|(?P<t_LBRACE>\\{)|(?P<t_PERIOD>\\.)|(?P<t_DIVEQUAL>/=)|(?P<t_XOR>\\^)|(?P<t_RBRACKET>\\])|(?P<t_GE>>=)|(?P<t_RPAREN>\\))|(?P<t_ANDEQUAL>&=)|(?P<t_TIMES>\\*)|(?P<t_PLUS>\\+)|(?P<t_COMMA>,)|(?P<t_MOD>%)|(?P<t_DIVIDE>/)|(?P<t_LT><)|(?P<t_SEMI>;)|(?P<t_MINUS>-)|(?P<t_EQUALS>=)|(?P<t_GT>>)', [None, ('t_NEWLINE', 'NEWLINE'), ('t_ID', 'ID'), ('t_comment', 'comment'), None, (None, 'PLUSPLUS'), (None, 'TIMESEQUAL'), (None, 'AND'), (None, 'NOT'), (None, 'OREQUAL'), (None, 'PLUSEQUAL'), (None, 'XOREQUAL'), (None, 'LE'), (None, 'LBRACKET'), (None, 'NE'), (None, 'RBRACE'), (None, 'MINUSEQUAL'), (None, 'EQ'), (None, 'MINUSMINUS'), (None, 'MODEQUAL'), (None, 'LPAREN'), (None, 'OR'), (None, 'LBRACE'), (None, 'PERIOD'), (None, 'DIVEQUAL'), (None, 'XOR'), (None, 'RBRACKET'), (None, 'GE'), (None, 'RPAREN'), (None, 'ANDEQUAL'), (None, 'TIMES'), (None, 'PLUS'), (None, 'COMMA'), (None, 'MOD'), (None, 'DIVIDE'), (None, 'LT'), (None, 'SEMI'), (None, 'MINUS'), (None, 'EQUALS'), (None, 'GT')])]}
_lexstateignore = {'INITIAL': ' \t'}
_lexstateerrorf = {'INITIAL': 't_error'}
