
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xcaE\xc4x\x91\x13\xd6\xa9\xe3\xb2+\x94\xc2\xa86\x1b'
    
_lr_action_items = {'RPAREN':([8,],[9,]),'STRING':([6,],[8,]),'SEMI':([9,],[10,]),'LPAREN':([2,],[6,]),'error':([0,],[4,]),'PRINT':([0,1,3,4,5,7,10,],[2,-2,2,-3,-4,-1,-5,]),'$end':([1,3,4,5,7,10,],[-2,0,-3,-4,-1,-5,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'print_statement':([0,3,],[5,5,]),'io_statement':([0,3,],[1,7,]),'program':([0,],[3,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> program io_statement','program',2,'p_program','/home/mc/classes/w4115/local/localparse.py',19),
  ('program -> io_statement','program',1,'p_program','/home/mc/classes/w4115/local/localparse.py',20),
  ('program -> error','program',1,'p_program_error','/home/mc/classes/w4115/local/localparse.py',26),
  ('io_statement -> print_statement','io_statement',1,'p_io_statement','/home/mc/classes/w4115/local/localparse.py',31),
  ('print_statement -> PRINT LPAREN STRING RPAREN SEMI','print_statement',5,'p______print_statement','/home/mc/classes/w4115/local/localparse.py',34),
]
